transition: low_rank
observation: affine
train_noise_z: true
train_noise_z_t0: true
init_noise_z: .05
init_noise_z_t0: 1
noise_z: "diag"
noise_z_t0: "diag"
identity_readout: false
activation: clipped_relu
decay: .9
readout_from: "z"
train_obs_bias: true
train_obs_weights: true
train_neuron_bias: true
weight_dist: uniform
initial_state: zero
obs_nonlinearity: softplus
obs_likelihood: Poisson
simulate_input: false
